name: Build
on: [pull_request, push]
jobs:
  
  androidTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: bash ./gradlew test --stacktrace


