name: Build
on: [pull_request, push]
jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Android Emulator Runner
        uses: ReactiveCircus/android-emulator-runner@v2.13.0
        with:
          api-level: 23
          script: ./gradlew connectedCheck
