name: Build
on: [pull_request, push]
jobs:
  test:
    name: Run Unit Tests
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Android Emulator Runner
  # You may pin to the exact commit or the version.
  # uses: ReactiveCircus/android-emulator-runner@e08f702234bdc95883c7fd5c7d2867ccf1a8463b
        uses: vgaidarji/android-github-actions-emulator@v1.0.1
