name: Build
on: [pull_request, push]
jobs:
  test:
    name: Run Unit Tests
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Unit tests
        run: bash ./gradlew test --stacktrace
      - name: Run Instrumentation Tests
        uses: malinskiy/action-android/emulator-run-cmd@release/0.0.5
        with:
          cmd: ./gradlew integrationTest
          api: 29
          tag: default
          abi: x86


